// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * About field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.about
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about: prismic.RichTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<AboutDocumentData>,
  "about",
  Lang
>;

type BlogPostDocumentDataSlicesSlice = BlogQuoteSlice | CodeSnippetSlice | ContentSlice;

/**
 * Item in *Blog Post → Tags*
 */
export interface BlogPostDocumentDataTagsItem {
  /**
   * Tag field in *Blog Post → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Post Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.postTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  postTitle: prismic.KeyTextField;

  /**
   * Post Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.postImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  postImage: prismic.ImageField<never>;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.publishDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishDate: prismic.DateField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogPost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogPost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Tags field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.tags[]
   * - **Tab**: Tags
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  tags: prismic.GroupField<Simplify<BlogPostDocumentDataTagsItem>>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blogPost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BlogPostDocumentData>,
  "blogPost",
  Lang
>;

type PageDocumentDataSlicesSlice =
  | BlogPostsSlice
  | HomeHeroSlice
  | ProjectsSlice
  | AboutSlice
  | ServicesSlice
  | ClientLogosSlice
  | TechStatsSlice
  | WorkStatsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadescription
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PageDocumentData>,
  "page",
  Lang
>;

type ProjectDocumentDataSlicesSlice = never;

/**
 * Content for Work documents
 */
interface ProjectDocumentData {
  /**
   * Name field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Url field in *Work*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Description field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Main Image field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.mainImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainImage: prismic.ImageField<never>;

  /**
   * Role field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Technologies field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.technologies
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  technologies: prismic.KeyTextField;

  /**
   * Company Description field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.companyDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  companyDescription: prismic.KeyTextField;

  /**
   * Date field in *Work*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Technologies field in *Work*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.technologies2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  technologies2: prismic.ContentRelationshipField<"technology">;

  /**
   * Logo field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ProjectDocumentData>,
  "project",
  Lang
>;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ServiceDocumentData>,
  "service",
  Lang
>;

/**
 * Content for Technology documents
 */
interface TechnologyDocumentData {
  /**
   * Name field in *Technology*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technology.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Priority field in *Technology*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: technology.priority
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  priority: prismic.NumberField;
}

/**
 * Technology document from Prismic
 *
 * - **API ID**: `technology`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<TechnologyDocumentData>,
  "technology",
  Lang
>;

export type AllDocumentTypes =
  | AboutDocument
  | BlogPostDocument
  | PageDocument
  | ProjectDocument
  | ServiceDocument
  | TechnologyDocument;

/**
 * Primary content in *About → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Title field in *About → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * About field in *About → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.about
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about: prismic.RichTextField;

  /**
   * Show More field in *About → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: about.primary.showMore
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showMore: prismic.BooleanField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *BlogHeroImage → Primary*
 */
export interface BlogHeroSliceDefaultPrimary {
  /**
   * Hero Image field in *BlogHeroImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_hero.primary.heroImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroImage: prismic.ImageField<never>;
}

/**
 * Default variation for BlogHeroImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogHeroImage*
 */
type BlogHeroSliceVariation = BlogHeroSliceDefault;

/**
 * BlogHeroImage Shared Slice
 *
 * - **API ID**: `blog_hero`
 * - **Description**: BlogHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogHeroSlice = prismic.SharedSlice<"blog_hero", BlogHeroSliceVariation>;

/**
 * Primary content in *BlogPosts → Primary*
 */
export interface BlogPostsSliceDefaultPrimary {
  /**
   * Title field in *BlogPosts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show more field in *BlogPosts → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_posts.primary.showMore
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showMore: prismic.BooleanField;
}

/**
 * Default variation for BlogPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPosts*
 */
type BlogPostsSliceVariation = BlogPostsSliceDefault;

/**
 * BlogPosts Shared Slice
 *
 * - **API ID**: `blog_posts`
 * - **Description**: BlogPosts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostsSlice = prismic.SharedSlice<"blog_posts", BlogPostsSliceVariation>;

/**
 * Primary content in *BlogQuote → Primary*
 */
export interface BlogQuoteSliceDefaultPrimary {
  /**
   * Quote field in *BlogQuote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * Default variation for BlogQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogQuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogQuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogQuote*
 */
type BlogQuoteSliceVariation = BlogQuoteSliceDefault;

/**
 * BlogQuote Shared Slice
 *
 * - **API ID**: `blog_quote`
 * - **Description**: BlogQuote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogQuoteSlice = prismic.SharedSlice<"blog_quote", BlogQuoteSliceVariation>;

/**
 * Primary content in *ClientLogos → Primary*
 */
export interface ClientLogosSliceDefaultPrimary {
  /**
   * Title field in *ClientLogos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *ClientLogos → Items*
 */
export interface ClientLogosSliceDefaultItem {
  /**
   * Client Logo field in *ClientLogos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.items[].clientLogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  clientLogo: prismic.ImageField<never>;

  /**
   * Link field in *ClientLogos → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for ClientLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: ClientLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientLogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClientLogosSliceDefaultPrimary>,
  Simplify<ClientLogosSliceDefaultItem>
>;

/**
 * Slice variation for *ClientLogos*
 */
type ClientLogosSliceVariation = ClientLogosSliceDefault;

/**
 * ClientLogos Shared Slice
 *
 * - **API ID**: `client_logos`
 * - **Description**: ClientLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientLogosSlice = prismic.SharedSlice<"client_logos", ClientLogosSliceVariation>;

/**
 * Primary content in *CodeSnippet → Primary*
 */
export interface CodeSnippetSliceDefaultPrimary {
  /**
   * Code field in *CodeSnippet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_snippet.primary.code
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  code: prismic.RichTextField;

  /**
   * Added lines field in *CodeSnippet → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_snippet.primary.addedLines
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  addedLines: prismic.KeyTextField;

  /**
   * Removed Lines field in *CodeSnippet → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_snippet.primary.removedLines
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  removedLines: prismic.KeyTextField;
}

/**
 * Default variation for CodeSnippet Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSnippetSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CodeSnippetSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CodeSnippet*
 */
type CodeSnippetSliceVariation = CodeSnippetSliceDefault;

/**
 * CodeSnippet Shared Slice
 *
 * - **API ID**: `code_snippet`
 * - **Description**: CodeSnippet
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSnippetSlice = prismic.SharedSlice<"code_snippet", CodeSnippetSliceVariation>;

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Content field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSlice = prismic.SharedSlice<"content", ContentSliceVariation>;

/**
 * Primary content in *HomeHero → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * Tagline One field in *HomeHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.taglineOne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  taglineOne: prismic.KeyTextField;

  /**
   * Tagline Two field in *HomeHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.taglineTwo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  taglineTwo: prismic.RichTextField;

  /**
   * Tagline Three field in *HomeHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.taglineThree
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  taglineThree: prismic.RichTextField;

  /**
   * Tagline Four field in *HomeHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.taglineFour
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  taglineFour: prismic.KeyTextField;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<"home_hero", HomeHeroSliceVariation>;

/**
 * Primary content in *Work → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Title field in *Work → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show More field in *Work → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: projects.primary.showMore
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showMore: prismic.BooleanField;
}

/**
 * Default variation for Work Slice
 *
 * - **API ID**: `default`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Work*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Work Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<"projects", ProjectsSliceVariation>;

/**
 * Primary content in *TechStats → Primary*
 */
export interface TechStatsSliceDefaultPrimary {
  /**
   * Title field in *TechStats → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_stats.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * React field in *TechStats → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_stats.primary.react
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  react: prismic.DateField;

  /**
   * Next field in *TechStats → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_stats.primary.next
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  next: prismic.DateField;

  /**
   * GraphQL field in *TechStats → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_stats.primary.graphql
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  graphql: prismic.DateField;

  /**
   * CSS field in *TechStats → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_stats.primary.css
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  css: prismic.DateField;
}

/**
 * Default variation for TechStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: TechStats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechStatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TechStatsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TechStats*
 */
type TechStatsSliceVariation = TechStatsSliceDefault;

/**
 * TechStats Shared Slice
 *
 * - **API ID**: `tech_stats`
 * - **Description**: TechStats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechStatsSlice = prismic.SharedSlice<"tech_stats", TechStatsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogPostDocumentDataTagsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      TechnologyDocument,
      TechnologyDocumentData,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      BlogHeroSlice,
      BlogHeroSliceDefaultPrimary,
      BlogHeroSliceVariation,
      BlogHeroSliceDefault,
      BlogPostsSlice,
      BlogPostsSliceDefaultPrimary,
      BlogPostsSliceVariation,
      BlogPostsSliceDefault,
      BlogQuoteSlice,
      BlogQuoteSliceDefaultPrimary,
      BlogQuoteSliceVariation,
      BlogQuoteSliceDefault,
      ClientLogosSlice,
      ClientLogosSliceDefaultPrimary,
      ClientLogosSliceDefaultItem,
      ClientLogosSliceVariation,
      ClientLogosSliceDefault,
      CodeSnippetSlice,
      CodeSnippetSliceDefaultPrimary,
      CodeSnippetSliceVariation,
      CodeSnippetSliceDefault,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      TechStatsSlice,
      TechStatsSliceDefaultPrimary,
      TechStatsSliceVariation,
      TechStatsSliceDefault,
    };
  }
}
