// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for About documents */
interface AboutDocumentData {
    /**
     * About field in *About*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.about
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about: prismicT.RichTextField;
}
/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HomeHeroSlice | ProjectsSlice | AboutSlice | ServicesSlice | ClientLogosSlice | TechStatsSlice | WorkStatsSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Work documents */
interface ProjectDocumentData {
    /**
     * Name field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Url field in *Work*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: project.url
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    url: prismicT.LinkField;
    /**
     * Description field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Main Image field in *Work*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.mainImage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    mainImage: prismicT.ImageField<never>;
    /**
     * Role field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.role
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    role: prismicT.KeyTextField;
    /**
     * Technologies field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.technologies
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    technologies: prismicT.KeyTextField;
    /**
     * Company Description field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.companyDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    companyDescription: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Work*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProjectDocumentDataSlicesSlice>;
}
/**
 * Slice for *Work → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice = ProjectSolutionSlice | ProjectImagesSlice | ProjectChallengeSlice;
/**
 * Work document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
/** Content for Service documents */
interface ServiceDocumentData {
    /**
     * Title field in *Service*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Service*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ServiceDocumentData>, "service", Lang>;
/** Content for Technology documents */
interface TechnologyDocumentData {
    /**
     * Name field in *Technology*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: technology.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
}
/**
 * Technology document from Prismic
 *
 * - **API ID**: `technology`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologyDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TechnologyDocumentData>, "technology", Lang>;
export type AllDocumentTypes = AboutDocument | PageDocument | ProjectDocument | ServiceDocument | TechnologyDocument;
/**
 * Primary content in About → Primary
 *
 */
interface AboutSliceDefaultPrimary {
    /**
     * Title field in *About → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * About field in *About → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.primary.about
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about: prismicT.RichTextField;
    /**
     * Show More field in *About → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: about.primary.showMore
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    showMore: prismicT.BooleanField;
}
/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: `About`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AboutSliceDefaultPrimary>, never>;
/**
 * Slice variation for *About*
 *
 */
type AboutSliceVariation = AboutSliceDefault;
/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: `About`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSlice = prismicT.SharedSlice<"about", AboutSliceVariation>;
/**
 * Primary content in ClientLogos → Primary
 *
 */
interface ClientLogosSliceDefaultPrimary {
    /**
     * Title field in *ClientLogos → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in ClientLogos → Items
 *
 */
export interface ClientLogosSliceDefaultItem {
    /**
     * Client Logo field in *ClientLogos → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.items[].clientLogo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    clientLogo: prismicT.ImageField<never>;
}
/**
 * Default variation for ClientLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ClientLogos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientLogosSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ClientLogosSliceDefaultPrimary>, Simplify<ClientLogosSliceDefaultItem>>;
/**
 * Slice variation for *ClientLogos*
 *
 */
type ClientLogosSliceVariation = ClientLogosSliceDefault;
/**
 * ClientLogos Shared Slice
 *
 * - **API ID**: `client_logos`
 * - **Description**: `ClientLogos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientLogosSlice = prismicT.SharedSlice<"client_logos", ClientLogosSliceVariation>;
/**
 * Primary content in HomeHero → Primary
 *
 */
interface HomeHeroSliceDefaultPrimary {
    /**
     * Tagline One field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineOne
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineOne: prismicT.KeyTextField;
    /**
     * Tagline Two field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineTwo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineTwo: prismicT.KeyTextField;
    /**
     * Tagline Three field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineThree
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineThree: prismicT.KeyTextField;
    /**
     * Tagline Four field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineFour
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineFour: prismicT.KeyTextField;
}
/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HomeHero*
 *
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;
/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSlice = prismicT.SharedSlice<"home_hero", HomeHeroSliceVariation>;
/**
 * Primary content in WorkChallenge → Primary
 *
 */
interface ProjectChallengeSliceDefaultPrimary {
    /**
     * Challenge field in *WorkChallenge → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_challenge.primary.challenge
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    challenge: prismicT.RichTextField;
}
/**
 * Default variation for WorkChallenge Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectChallenge`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectChallengeSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectChallengeSliceDefaultPrimary>, never>;
/**
 * Slice variation for *WorkChallenge*
 *
 */
type ProjectChallengeSliceVariation = ProjectChallengeSliceDefault;
/**
 * WorkChallenge Shared Slice
 *
 * - **API ID**: `project_challenge`
 * - **Description**: `ProjectChallenge`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectChallengeSlice = prismicT.SharedSlice<"project_challenge", ProjectChallengeSliceVariation>;
/**
 * Primary content in WorkImages → Primary
 *
 */
interface ProjectImagesSliceDefaultPrimary {
    /**
     * Title field in *WorkImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_images.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in WorkImages → Items
 *
 */
export interface ProjectImagesSliceDefaultItem {
    /**
     * Image field in *WorkImages → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_images.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for WorkImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectImagesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectImagesSliceDefaultPrimary>, Simplify<ProjectImagesSliceDefaultItem>>;
/**
 * Slice variation for *WorkImages*
 *
 */
type ProjectImagesSliceVariation = ProjectImagesSliceDefault;
/**
 * WorkImages Shared Slice
 *
 * - **API ID**: `project_images`
 * - **Description**: `ProjectImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectImagesSlice = prismicT.SharedSlice<"project_images", ProjectImagesSliceVariation>;
/**
 * Primary content in WorkSolution → Primary
 *
 */
interface ProjectSolutionSliceDefaultPrimary {
    /**
     * Solution field in *WorkSolution → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_solution.primary.solution
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    solution: prismicT.RichTextField;
}
/**
 * Default variation for WorkSolution Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectSolution`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSolutionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectSolutionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *WorkSolution*
 *
 */
type ProjectSolutionSliceVariation = ProjectSolutionSliceDefault;
/**
 * WorkSolution Shared Slice
 *
 * - **API ID**: `project_solution`
 * - **Description**: `ProjectSolution`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSolutionSlice = prismicT.SharedSlice<"project_solution", ProjectSolutionSliceVariation>;
/**
 * Primary content in Work → Primary
 *
 */
interface ProjectsSliceDefaultPrimary {
    /**
     * Title field in *Work → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Show More field in *Work → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: projects.primary.showMore
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    showMore: prismicT.BooleanField;
}
/**
 * Item in Work → Items
 *
 */
export interface ProjectsSliceDefaultItem {
    /**
     * Work field in *Work → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.items[].work
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    work: prismicT.RelationField<"project">;
}
/**
 * Default variation for Work Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Projects`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectsSliceDefaultPrimary>, Simplify<ProjectsSliceDefaultItem>>;
/**
 * Slice variation for *Work*
 *
 */
type ProjectsSliceVariation = ProjectsSliceDefault;
/**
 * Work Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: `Projects`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSlice = prismicT.SharedSlice<"projects", ProjectsSliceVariation>;
/**
 * Primary content in Services → Primary
 *
 */
interface ServicesSliceDefaultPrimary {
    /**
     * Title field in *Services → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in Services → Items
 *
 */
export interface ServicesSliceDefaultItem {
    /**
     * Services field in *Services → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].services
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    services: prismicT.RelationField<"service">;
}
/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ServicesSliceDefaultPrimary>, Simplify<ServicesSliceDefaultItem>>;
/**
 * Slice variation for *Services*
 *
 */
type ServicesSliceVariation = ServicesSliceDefault;
/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSlice = prismicT.SharedSlice<"services", ServicesSliceVariation>;
/**
 * Primary content in TechStats → Primary
 *
 */
interface TechStatsSliceDefaultPrimary {
    /**
     * Title field in *TechStats → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tech_stats.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * React field in *TechStats → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tech_stats.primary.react
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    react: prismicT.KeyTextField;
    /**
     * Next field in *TechStats → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tech_stats.primary.next
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    next: prismicT.KeyTextField;
}
/**
 * Default variation for TechStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TechStats`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TechStatsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TechStatsSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TechStats*
 *
 */
type TechStatsSliceVariation = TechStatsSliceDefault;
/**
 * TechStats Shared Slice
 *
 * - **API ID**: `tech_stats`
 * - **Description**: `TechStats`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TechStatsSlice = prismicT.SharedSlice<"tech_stats", TechStatsSliceVariation>;
/**
 * Primary content in WorkStats → Primary
 *
 */
interface WorkStatsSliceDefaultPrimary {
    /**
     * React field in *WorkStats → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work_stats.primary.react
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    react: prismicT.KeyTextField;
    /**
     * Next field in *WorkStats → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work_stats.primary.next
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    next: prismicT.KeyTextField;
}
/**
 * Default variation for WorkStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: `WorkStats`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkStatsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<WorkStatsSliceDefaultPrimary>, never>;
/**
 * Slice variation for *WorkStats*
 *
 */
type WorkStatsSliceVariation = WorkStatsSliceDefault;
/**
 * WorkStats Shared Slice
 *
 * - **API ID**: `work_stats`
 * - **Description**: `WorkStats`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkStatsSlice = prismicT.SharedSlice<"work_stats", WorkStatsSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AboutDocumentData, AboutDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, ProjectDocumentData, ProjectDocumentDataSlicesSlice, ProjectDocument, ServiceDocumentData, ServiceDocument, TechnologyDocumentData, TechnologyDocument, AllDocumentTypes, AboutSliceDefaultPrimary, AboutSliceDefault, AboutSliceVariation, AboutSlice, ClientLogosSliceDefaultPrimary, ClientLogosSliceDefaultItem, ClientLogosSliceDefault, ClientLogosSliceVariation, ClientLogosSlice, HomeHeroSliceDefaultPrimary, HomeHeroSliceDefault, HomeHeroSliceVariation, HomeHeroSlice, ProjectChallengeSliceDefaultPrimary, ProjectChallengeSliceDefault, ProjectChallengeSliceVariation, ProjectChallengeSlice, ProjectImagesSliceDefaultPrimary, ProjectImagesSliceDefaultItem, ProjectImagesSliceDefault, ProjectImagesSliceVariation, ProjectImagesSlice, ProjectSolutionSliceDefaultPrimary, ProjectSolutionSliceDefault, ProjectSolutionSliceVariation, ProjectSolutionSlice, ProjectsSliceDefaultPrimary, ProjectsSliceDefaultItem, ProjectsSliceDefault, ProjectsSliceVariation, ProjectsSlice, ServicesSliceDefaultPrimary, ServicesSliceDefaultItem, ServicesSliceDefault, ServicesSliceVariation, ServicesSlice, TechStatsSliceDefaultPrimary, TechStatsSliceDefault, TechStatsSliceVariation, TechStatsSlice, WorkStatsSliceDefaultPrimary, WorkStatsSliceDefault, WorkStatsSliceVariation, WorkStatsSlice };
    }
}
