// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HomeHeroSlice | ProjectsSlice | AboutSlice | ServicesSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Project documents */
interface ProjectDocumentData {
    /**
     * Name field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Url field in *Project*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: project.url
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    url: prismicT.LinkField;
    /**
     * Description field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Main Image field in *Project*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.mainImage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    mainImage: prismicT.ImageField<never>;
    /**
     * Role field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.role
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    role: prismicT.KeyTextField;
    /**
     * Technologies field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.technologies
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    technologies: prismicT.KeyTextField;
    /**
     * Company Description field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.companyDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    companyDescription: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Project*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProjectDocumentDataSlicesSlice>;
}
/**
 * Slice for *Project → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice = ProjectSolutionSlice | ProjectImagesSlice | ProjectChallengeSlice;
/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
/** Content for Service documents */
interface ServiceDocumentData {
    /**
     * Title field in *Service*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Service*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ServiceDocumentData>, "service", Lang>;
/** Content for Technology documents */
interface TechnologyDocumentData {
    /**
     * Name field in *Technology*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: technology.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
}
/**
 * Technology document from Prismic
 *
 * - **API ID**: `technology`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologyDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TechnologyDocumentData>, "technology", Lang>;
export type AllDocumentTypes = PageDocument | ProjectDocument | ServiceDocument | TechnologyDocument;
/**
 * Primary content in About → Primary
 *
 */
interface AboutSliceDefaultPrimary {
    /**
     * Title field in *About → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * About field in *About → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.primary.about
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about: prismicT.RichTextField;
}
/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: `About`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AboutSliceDefaultPrimary>, never>;
/**
 * Slice variation for *About*
 *
 */
type AboutSliceVariation = AboutSliceDefault;
/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: `About`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSlice = prismicT.SharedSlice<"about", AboutSliceVariation>;
/**
 * Primary content in HomeHero → Primary
 *
 */
interface HomeHeroSliceDefaultPrimary {
    /**
     * Tagline One field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineOne
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineOne: prismicT.KeyTextField;
    /**
     * Tagline Two field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineTwo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineTwo: prismicT.KeyTextField;
    /**
     * Tagline Three field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineThree
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineThree: prismicT.KeyTextField;
    /**
     * Tagline Four field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineFour
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineFour: prismicT.KeyTextField;
}
/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HomeHero*
 *
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;
/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSlice = prismicT.SharedSlice<"home_hero", HomeHeroSliceVariation>;
/**
 * Primary content in ProjectChallenge → Primary
 *
 */
interface ProjectChallengeSliceDefaultPrimary {
    /**
     * Challenge field in *ProjectChallenge → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_challenge.primary.challenge
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    challenge: prismicT.RichTextField;
}
/**
 * Default variation for ProjectChallenge Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectChallenge`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectChallengeSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectChallengeSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ProjectChallenge*
 *
 */
type ProjectChallengeSliceVariation = ProjectChallengeSliceDefault;
/**
 * ProjectChallenge Shared Slice
 *
 * - **API ID**: `project_challenge`
 * - **Description**: `ProjectChallenge`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectChallengeSlice = prismicT.SharedSlice<"project_challenge", ProjectChallengeSliceVariation>;
/**
 * Primary content in ProjectImages → Primary
 *
 */
interface ProjectImagesSliceDefaultPrimary {
    /**
     * Title field in *ProjectImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_images.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in ProjectImages → Items
 *
 */
export interface ProjectImagesSliceDefaultItem {
    /**
     * Image field in *ProjectImages → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_images.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ProjectImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectImagesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectImagesSliceDefaultPrimary>, Simplify<ProjectImagesSliceDefaultItem>>;
/**
 * Slice variation for *ProjectImages*
 *
 */
type ProjectImagesSliceVariation = ProjectImagesSliceDefault;
/**
 * ProjectImages Shared Slice
 *
 * - **API ID**: `project_images`
 * - **Description**: `ProjectImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectImagesSlice = prismicT.SharedSlice<"project_images", ProjectImagesSliceVariation>;
/**
 * Primary content in ProjectSolution → Primary
 *
 */
interface ProjectSolutionSliceDefaultPrimary {
    /**
     * Solution field in *ProjectSolution → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_solution.primary.solution
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    solution: prismicT.RichTextField;
}
/**
 * Default variation for ProjectSolution Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectSolution`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSolutionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectSolutionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ProjectSolution*
 *
 */
type ProjectSolutionSliceVariation = ProjectSolutionSliceDefault;
/**
 * ProjectSolution Shared Slice
 *
 * - **API ID**: `project_solution`
 * - **Description**: `ProjectSolution`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSolutionSlice = prismicT.SharedSlice<"project_solution", ProjectSolutionSliceVariation>;
/**
 * Primary content in Projects → Primary
 *
 */
interface ProjectsSliceDefaultPrimary {
    /**
     * Title field in *Projects → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in Projects → Items
 *
 */
export interface ProjectsSliceDefaultItem {
    /**
     * Projects field in *Projects → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.items[].projects
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    projects: prismicT.RelationField<"project">;
}
/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Projects`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectsSliceDefaultPrimary>, Simplify<ProjectsSliceDefaultItem>>;
/**
 * Slice variation for *Projects*
 *
 */
type ProjectsSliceVariation = ProjectsSliceDefault;
/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: `Projects`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSlice = prismicT.SharedSlice<"projects", ProjectsSliceVariation>;
/**
 * Primary content in Services → Primary
 *
 */
interface ServicesSliceDefaultPrimary {
    /**
     * Title field in *Services → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in Services → Items
 *
 */
export interface ServicesSliceDefaultItem {
    /**
     * Services field in *Services → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].services
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    services: prismicT.RelationField<"service">;
}
/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ServicesSliceDefaultPrimary>, Simplify<ServicesSliceDefaultItem>>;
/**
 * Slice variation for *Services*
 *
 */
type ServicesSliceVariation = ServicesSliceDefault;
/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSlice = prismicT.SharedSlice<"services", ServicesSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, ProjectDocumentData, ProjectDocumentDataSlicesSlice, ProjectDocument, ServiceDocumentData, ServiceDocument, TechnologyDocumentData, TechnologyDocument, AllDocumentTypes, AboutSliceDefaultPrimary, AboutSliceDefault, AboutSliceVariation, AboutSlice, HomeHeroSliceDefaultPrimary, HomeHeroSliceDefault, HomeHeroSliceVariation, HomeHeroSlice, ProjectChallengeSliceDefaultPrimary, ProjectChallengeSliceDefault, ProjectChallengeSliceVariation, ProjectChallengeSlice, ProjectImagesSliceDefaultPrimary, ProjectImagesSliceDefaultItem, ProjectImagesSliceDefault, ProjectImagesSliceVariation, ProjectImagesSlice, ProjectSolutionSliceDefaultPrimary, ProjectSolutionSliceDefault, ProjectSolutionSliceVariation, ProjectSolutionSlice, ProjectsSliceDefaultPrimary, ProjectsSliceDefaultItem, ProjectsSliceDefault, ProjectsSliceVariation, ProjectsSlice, ServicesSliceDefaultPrimary, ServicesSliceDefaultItem, ServicesSliceDefault, ServicesSliceVariation, ServicesSlice };
    }
}
