// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HomeHeroSlice | ProjectsSlice | AboutSlice | ServicesSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Project documents */
interface ProjectDocumentData {
    /**
     * Name field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Description field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Main Image field in *Project*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.mainImage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    mainImage: prismicT.ImageField<never>;
    /**
     * Technologies field in *Project*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: project.technologies
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    technologies: prismicT.RelationField<"technology">;
}
/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
/** Content for Service documents */
type ServiceDocumentData = Record<string, never>;
/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ServiceDocumentData>, "service", Lang>;
/** Content for Technology documents */
interface TechnologyDocumentData {
    /**
     * Name field in *Technology*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: technology.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Logo field in *Technology*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: technology.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Technology document from Prismic
 *
 * - **API ID**: `technology`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologyDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TechnologyDocumentData>, "technology", Lang>;
export type AllDocumentTypes = PageDocument | ProjectDocument | ServiceDocument | TechnologyDocument;
/**
 * Primary content in About → Primary
 *
 */
interface AboutSliceDefaultPrimary {
    /**
     * Title field in *About → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * About field in *About → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.primary.about
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about: prismicT.KeyTextField;
}
/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: `About`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AboutSliceDefaultPrimary>, never>;
/**
 * Slice variation for *About*
 *
 */
type AboutSliceVariation = AboutSliceDefault;
/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: `About`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSlice = prismicT.SharedSlice<"about", AboutSliceVariation>;
/**
 * Primary content in HomeHero → Primary
 *
 */
interface HomeHeroSliceDefaultPrimary {
    /**
     * Tagline One field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineOne
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineOne: prismicT.KeyTextField;
    /**
     * Tagline Two field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineTwo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineTwo: prismicT.KeyTextField;
    /**
     * Tagline Three field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineThree
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineThree: prismicT.KeyTextField;
    /**
     * Tagline Four field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.taglineFour
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taglineFour: prismicT.KeyTextField;
}
/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HomeHero*
 *
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;
/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSlice = prismicT.SharedSlice<"home_hero", HomeHeroSliceVariation>;
/**
 * Primary content in Projects → Primary
 *
 */
interface ProjectsSliceDefaultPrimary {
    /**
     * Title field in *Projects → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in Projects → Items
 *
 */
export interface ProjectsSliceDefaultItem {
    /**
     * Projects field in *Projects → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.items[].projects
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    projects: prismicT.RelationField<"project">;
}
/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Projects`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectsSliceDefaultPrimary>, Simplify<ProjectsSliceDefaultItem>>;
/**
 * Slice variation for *Projects*
 *
 */
type ProjectsSliceVariation = ProjectsSliceDefault;
/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: `Projects`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSlice = prismicT.SharedSlice<"projects", ProjectsSliceVariation>;
/**
 * Primary content in Services → Primary
 *
 */
interface ServicesSliceDefaultPrimary {
    /**
     * Title field in *Services → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in Services → Items
 *
 */
export interface ServicesSliceDefaultItem {
    /**
     * Services field in *Services → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].services
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    services: prismicT.RelationField<"service">;
}
/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ServicesSliceDefaultPrimary>, Simplify<ServicesSliceDefaultItem>>;
/**
 * Slice variation for *Services*
 *
 */
type ServicesSliceVariation = ServicesSliceDefault;
/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSlice = prismicT.SharedSlice<"services", ServicesSliceVariation>;
/**
 * Primary content in SocialItem → Primary
 *
 */
interface SocialItemSliceDefaultPrimary {
    /**
     * Title field in *SocialItem → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: social_item.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Link field in *SocialItem → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: social_item.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for SocialItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SocialItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialItemSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SocialItemSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SocialItem*
 *
 */
type SocialItemSliceVariation = SocialItemSliceDefault;
/**
 * SocialItem Shared Slice
 *
 * - **API ID**: `social_item`
 * - **Description**: `SocialItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialItemSlice = prismicT.SharedSlice<"social_item", SocialItemSliceVariation>;
/**
 * Primary content in Socials → Primary
 *
 */
interface SocialsSliceDefaultPrimary {
    /**
     * Title field in *Socials → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: socials.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Socials → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: socials.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Socials Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Socials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SocialsSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Socials*
 *
 */
type SocialsSliceVariation = SocialsSliceDefault;
/**
 * Socials Shared Slice
 *
 * - **API ID**: `socials`
 * - **Description**: `Socials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialsSlice = prismicT.SharedSlice<"socials", SocialsSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, ProjectDocumentData, ProjectDocument, ServiceDocumentData, ServiceDocument, TechnologyDocumentData, TechnologyDocument, AllDocumentTypes, AboutSliceDefaultPrimary, AboutSliceDefault, AboutSliceVariation, AboutSlice, HomeHeroSliceDefaultPrimary, HomeHeroSliceDefault, HomeHeroSliceVariation, HomeHeroSlice, ProjectsSliceDefaultPrimary, ProjectsSliceDefaultItem, ProjectsSliceDefault, ProjectsSliceVariation, ProjectsSlice, ServicesSliceDefaultPrimary, ServicesSliceDefaultItem, ServicesSliceDefault, ServicesSliceVariation, ServicesSlice, SocialItemSliceDefaultPrimary, SocialItemSliceDefault, SocialItemSliceVariation, SocialItemSlice, SocialsSliceDefaultPrimary, SocialsSliceDefault, SocialsSliceVariation, SocialsSlice };
    }
}
