// Code generated by Slice Machine. DO NOT EDIT.

import About from './About';
import HomeHero from './HomeHero';
import ProjectChallenge from './ProjectChallenge';
import ProjectImages from './ProjectImages';
import ProjectSolution from './ProjectSolution';
import Projects from './Projects';
import Services from './Services';

export {
	About,
	HomeHero,
	ProjectChallenge,
	ProjectImages,
	ProjectSolution,
	Projects,
	Services,
};

export const components = {
	about: About,
	home_hero: HomeHero,
	project_challenge: ProjectChallenge,
	project_images: ProjectImages,
	project_solution: ProjectSolution,
	projects: Projects,
	services: Services,
};
