// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  blog_hero: dynamic(() => import("./BlogHeroImage")),
  blog_posts: dynamic(() => import("./BlogPosts")),
  client_logos: dynamic(() => import("./ClientLogos")),
  code_snippet: dynamic(() => import("./CodeSnippet")),
  content: dynamic(() => import("./Content")),
  home_hero: dynamic(() => import("./HomeHero")),
  projects: dynamic(() => import("./Work")),
  tech_stats: dynamic(() => import("./TechStats")),
};
