import "@/styles/globals.css";

import { PrismicPreview } from "@prismicio/next";
import { Poppins } from "next/font/google";
import { ReactNode } from "react";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import data from "@/data/portfolio.json";
import { repositoryName } from "@/slicemachine.config.json";

export const metadata = {
  title: data.name,
  description: "Generated by Next.js",
};

type LayoutProps = {
  children: ReactNode;
};

const poppins = Poppins({ weight: ["300", "500", "700"], subsets: ["latin"] });

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={`relative text-lg font-light ${poppins.className}`}>
        <div className="gradient-circle" />
        <div className="gradient-circle-bottom" />

        <div className="container mx-auto mb-10">
          <Header />

          {children}

          <Footer />

          <PrismicPreview repositoryName={repositoryName} />
        </div>
      </body>
    </html>
  );
}
